apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-ingress
  namespace: uptime-dev
spec:
  rules:
  - host: uptime.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uptime-service
            port:
              number: 80


